name: Release

on:
  push:
    tags:
      - v*

env:
  node-version: 12.x

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install Deps
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      # - name: Test
      #   run: yarn test

      - name: Setup authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish
        run: npm publish --access public
